import { useEffect } from "react";
import { siteConfig } from "../site-config";

interface SchemaMarkupProps {
  pageType?: "WebSite" | "LocalBusiness" | "Article" | "FAQPage";
  pageTitle?: string;
  pageUrl?: string;
  faqList?: { question: string; answer: string }[];
}

export default function SchemaMarkup({
  pageType = "WebSite",
  pageTitle,
  pageUrl = typeof window !== "undefined" ? window.location.href : "",
  faqList,
}: SchemaMarkupProps) {
  useEffect(() => {
    if (typeof window === "undefined") return;

    // 1. Remove existing schema scripts generated by this component to prevent duplicates
    const oldScripts = document.querySelectorAll("script[data-schema-type]");
    oldScripts.forEach((el) => el.remove());

    const currentUrl = pageUrl || window.location.href;
    const schemas: any[] = [];

    // 2. Base WebSite & SiteNavigationElement (Organic Sitelinks Optimization)
    if (pageType === "WebSite") {
      schemas.push({
        "@context": "https://schema.org",
        "@type": "WebSite",
        "@id": `${currentUrl}#website`,
        "url": currentUrl,
        "name": siteConfig.name,
        "description": siteConfig.description,
      });

      // Navigation links for Organic Sitelinks
      schemas.push({
        "@context": "https://schema.org",
        "@type": "SiteNavigationElement",
        "@id": `${currentUrl}#navigation`,
        "name": [
          "Home",
          ...siteConfig.services.map((s) => s.title),
          "Contact Us"
        ],
        "url": [
          currentUrl,
          ...siteConfig.services.map((s) => `${currentUrl.replace(/\/$/, "")}/services/${s.id}`),
          `${currentUrl.replace(/\/$/, "")}/contact`
        ]
      });
    }

    // 3. LocalBusiness Schema
    const addressParts = siteConfig.address ? siteConfig.address.split(",") : [];
    const inferredLocality = addressParts.length > 1 ? addressParts[addressParts.length - 1].trim() : "Johannesburg";

    schemas.push({
      "@context": "https://schema.org",
      "@type": "LocalBusiness",
      "@id": `${currentUrl}#localbusiness`,
      "name": siteConfig.name,
      "image": `${currentUrl.replace(/\/$/, "")}/logo.png`,
      "telephone": siteConfig.emergencyPhone,
      "email": siteConfig.contactEmail,
      "address": {
        "@type": "PostalAddress",
        "streetAddress": siteConfig.address,
        "addressLocality": (siteConfig as any).locality || inferredLocality,
        "addressCountry": (siteConfig as any).countryCode || "ZA"
      },
      "url": currentUrl
    });

    // 4. FAQ Schema (Crucial for Answer Engine Optimization - AEO)
    if (faqList && faqList.length > 0) {
      schemas.push({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqList.map((faq) => ({
          "@type": "Question",
          "name": faq.question,
          "acceptedAnswer": {
            "@type": "Answer",
            "text": faq.answer
          }
        }))
      });
    }

    // 5. Inject JSON-LD
    schemas.forEach((schema, idx) => {
      const script = document.createElement("script");
      script.type = "application/ld+json";
      script.setAttribute("data-schema-type", `${pageType}-${idx}`);
      script.innerHTML = JSON.stringify(schema);
      document.head.appendChild(script);
    });

    return () => {
      const cleanupScripts = document.querySelectorAll("script[data-schema-type]");
      cleanupScripts.forEach((el) => el.remove());
    };
  }, [pageType, pageTitle, pageUrl, faqList]);

  return null;
}
